server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: vms-user-service
  config:
    import: optional:configserver:https://config-server-production-9c39.up.railway.app
  datasource:
    url: ${DB_URL:jdbc:mysql://mainline.proxy.rlwy.net:49676/railway}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:hAFSMpYViCCbzqulXYKnXdVzdWgVJWdV}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: https://eureka-service-production-dbce.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    issuer: ${JWT_ISSUER:volunteer-user-service}
    secret: ${JWT_SECRET:}
    expires-in: ${JWT_EXPIRES_IN:3600}
    refresh-expires-in: ${JWT_REFRESH_EXPIRES_IN:604800}
